apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jgaew6hun-python 
  janus-idp.io/tekton: jgaew6hun-python
  backstage.io/kubernetes-id: jgaew6hun-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jgaew6hun-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  