apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jgaew6hun-python
  janus-idp.io/tekton: jgaew6hun-python
  backstage.io/kubernetes-id: jgaew6hun-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jgaew6hun-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
